export const DATA = [
  {
    id: 1122,
    type: "Mountain Bike",
    name: "Yeti SB6 T-Series X01 Eagle 27.5″",
    photoURL: "img/item4.jpg",
    photoURL_Hover: "img/item5.jpg",
    isHover: false,
    isSale: 35,
    price: 250,
  },
  {
    id: 1123,
    type: "Mountain Bike",
    name: "Giant Stance 2 27.5″",
    photoURL: "img/item6.jpg",
    photoURL_Hover: "img/item5.jpg",
    isHover: false,
    isSale: 25,
    price: 625,
  },
  {
    id: 1124,
    type: "Jump Bike",
    name: "A 2010 model year Cervélo RS",
    photoURL: "img/item8.jpg",
    photoURL_Hover: "img/item7.jpg",
    isHover: false,
    isSale: 20,
    price: 580,
  },
  {
    id: 1125,
    type: "Mountain Bike",
    name: "Cube Stereo 140 HPC SL 27.5″",
    photoURL: "img/item10.jpg",
    photoURL_Hover: "img/item9.jpg",
    isHover: false,
    isSale: null,
    price: 520,
  },
  {
    id: 1126,
    type: "Mountain Bike",
    name: "Ludovic Péron Trek Bicycle",
    photoURL: "img/item12.jpg",
    photoURL_Hover: "img/item11.jpg",
    isHover: false,
    isSale: null,
    price: 690,
  },
  {
    id: 1127,
    type: "Jump Bike",
    name: "Keanu Specialized Road Bike",
    photoURL: "img/item4.jpg",
    photoURL_Hover: "img/item5.jpg",
    isHover: false,
    isSale: null,
    price: 180,
  },
];
export const NEW_PRODUCT = [
  {
    id: 1122,
    type: "Mountain Bike",
    name: "Yeti SB6 T-Series X01 Eagle 27.5″",
    photoURL: "img/item4.jpg",
    photoURL_Hover: "img/item5.jpg",
    isHover: false,
    isSale: 35,
    price: 250,
  },
  {
    id: 1123,
    type: "Mountain Bike",
    name: "Giant Stance 2 27.5″",
    photoURL: "img/item6.jpg",
    photoURL_Hover: "img/item5.jpg",
    isHover: false,
    isSale: 25,
    price: 625,
  },
  {
    id: 1124,
    type: "Jump Bike",
    name: "A 2010 model year Cervélo RS",
    photoURL: "img/item8.jpg",
    photoURL_Hover: "img/item7.jpg",
    isHover: false,
    isSale: 20,
    price: 580,
  },
  {
    id: 1125,
    type: "Mountain Bike",
    name: "Cube Stereo 140 HPC SL 27.5″",
    photoURL: "img/item10.jpg",
    photoURL_Hover: "img/item9.jpg",
    isHover: false,
    isSale: null,
    price: 520,
  },
];
export const DATA_UPDATE = [
  {
    id: 1,
    date: "20 APR 2017",
    title: "New bike set-up instruction",
    imgURL: "img/update.jpg",
    content:
      "Parturient in potenti id rutrum duis torquent parturient sceler isque sit vestibulum a posuere scelerisque viverra urna. Egestas tristique sceler...",
  },
  {
    id: 2,
    date: "08 OCT 2014",
    title: "How to set your saddle height",
    imgURL: "img/update1.jpg",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiuasmod tempor incididunt....",
  },
  {
    id: 3,
    date: "8 OCT 2014",
    title: "Bike light comparison",
    imgURL: "img/update2.jpg",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiuasmod tempor incididunt....",
  },
];
